# Generated by Django 2.2.9 on 2020-06-09 12:07

from django.db import migrations, models
import fdfsstorage.backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('attachment', models.FileField(storage=fdfsstorage.backends.FdfsStorage, upload_to='test/upload/to/')),
            ],
        ),
    ]
